### ISSUE TITLE
图片上传和文件上传都会引发相同的错误

### ISSUE THREAD

**Issue by dashiell-zhang** [ant-design-blazor/ueditor-blazor#10]
我按照示例进行添加 富文本框之后，点击图片上传和文件上传都会出现下图中的错误，此刻似乎还有发起任何 http 文件传输请求

![image](https://user-images.githubusercontent.com/36178221/134632056-8e56c739-4db4-41c8-8dc2-7694ab3cf89e.png)

**Comment by charset** [comment]
`image.js:644`是 `editor.getOpt('imageUploadService')`
检查`neditor.service.js:25`
`window.UEDITOR_CONFIG['imageUploadService']`
函数是否正确定义？

**Comment by dashiell-zhang** [comment]
> `image.js:644`是 `editor.getOpt('imageUploadService')`
> 检查`neditor.service.js:25`
> `window.UEDITOR_CONFIG['imageUploadService']`
> 函数是否正确定义？

你好，我不太明白 window.UEDITOR_CONFIG['imageUploadService'] 这个是要定义什么，imageUploadService 时一个 js 方法的名称吗？

![image](https://user-images.githubusercontent.com/36178221/134790677-508ab48d-bc07-40a8-9b2c-382ba72f0685.png)

**Comment by dashiell-zhang** [comment]
我后面参照 https://gitee.com/notadd/neditor/blob/master/neditor.service.js  这里 添加了 如下的代码，也还是不对
![image](https://user-images.githubusercontent.com/36178221/134791374-5721b63e-5999-45fc-9e6e-44d9a48c15e4.png)

**Comment by dashiell-zhang** [comment]
![image](https://user-images.githubusercontent.com/36178221/134793933-786d7c76-b47a-483e-bde3-7776ba16b4ef.png)
问题解决了，服务定义的 js 写在  neditor.config.js 之后就可以了
