### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by patrykgz** [ant-design-blazor/ueditor-blazor#8]
Shows on Load
Uncaught TypeError: Cannot read property 'width' of undefined
    at UE.Editor.b (neditor.all.min.js:18)
    at UE.Editor.fireEvent (neditor.all.min.js:5)
    at c (neditor.all.min.js:6)
    at neditor.all.min.js:6
    at HTMLScriptElement.i.onload.i.onreadystatechange (neditor.all.min.js:5)

**Comment by shashikantx** [comment]
@ElderJames 

I am getting the same error, as mentioned above by @MutatePat 


am trying it on .net core 6 preview 5 blazor wasm

**Comment by ElderJames** [comment]
Please put the `uditor js files` on top of the `webassembly.js`:

```diff
+   <script src="_content/UEditorBlazor/neditor.config.js"></script>
+   <script src="_content/UEditorBlazor/neditor.all.min.js" defer></script>
+   <script src="_content/UEditorBlazor/ueditor-blazor.js"></script>

    <script src="_framework/blazor.webassembly.js"></script>
```

**Comment by shashikantx** [comment]
@ElderJames 

I just did that 

![image](https://user-images.githubusercontent.com/28926964/124926736-8086f880-e01b-11eb-877e-93862ccae1dc.png)

I still get the same error
![image](https://user-images.githubusercontent.com/28926964/124926824-97c5e600-e01b-11eb-9eda-9e1f25a11328.png)

**Comment by ElderJames** [comment]
@shashikantx @MutatePat Sorry, it's my mistake, I have fixed it.
